name: Deploy to Render

on:
  pull_request:
    types: [opened, synchronize, reopened, closed]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to Render
        uses: render-deploy-action
        with:
          render_token: ${{ secrets.RENDER_TOKEN }}
          args: --branch ${{ github.event.pull_request.head.ref }} --pr ${{ github.event.number }}


